<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 02 Mar 2022 13:12:43 +0000
 */

$conf['title'] = 'TX Wiki';
$conf['lang'] = 'zh';
$conf['template'] = 'vector';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
