<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Wed, 02 Mar 2022 12:26:48 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
