# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 02 Mar 2022 12:26:48 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$Mx5PbAiNzXQFdBZkziUUV.JWPQW.de3SkSIcV0G8BPQAAznAITvGy:admin:terminus202110@protonmail.com:admin,user
